public enum CommandEnum
{
    NONE,
    ENDTURN,
    UPGRADE_CHASIS,
    UPGRADE_ENGINE,
    UPGRADE_GUN,
    UPGRADE_STRUCTURE,
    UPGRADE_RADIO,
    MAKE_BANK,
    INSTANTIANE_UNIT,
    INSTANTIANE_STRUCTURE,
    MOVE,
    ATTACK,
    DEFEND
}
